### ISSUE TITLE
Date Fields

### ISSUE THREAD

**Issue by dncrews** [dncrews/angular-elastic-builder#2]

**Comment by linyi333** [comment]
Thinking of injecting the bootstrap-ui datepicker into it, any suggestion for start with?  just quickly update date.html template file and add the controller of it to configure the datepicker, but not sure how to trigger the data.query updating after select date.

**Comment by dncrews** [comment]
If you're using anything outside of Angular scope, you'll likely need to manually fire a `$scope.$digest` on its events

**Comment by oguennec** [comment]
I have integrated angular-ui for bootstrap in order to display the Calendar (ui.bootstrap.datepicker) while enhancing date search capabilities with term and range search.

Different date formats for different date fields can be selected from the builder.

Bootstrap JS dependency can be removed as a result of ui.bootstrap integration.

Here is the outlook of the filter builder with the datepicker.

![filterswithcalendar](https://cloud.githubusercontent.com/assets/6723310/14424743/c5701566-ffda-11e5-8204-9f4d46c5aec4.png)

**Comment by oguennec** [comment]
[Pull request](https://github.com/dncrews/angular-elastic-builder/pull/4/)
